reference_name = "liver"
min_percentile = 0.1
LRI_database = "CPDBv5.0.0"

[celltype]
"plasma cell" = 1730
"mature B cell" = 663
"hepatic stellate cell" = 3997
"vein endothelial cell" = 287
"vascular associated smooth muscle cell" = 6811
"fibroblast" = 1313
"alpha-beta T cell" = 1735
"natural killer cell" = 73397
"gamma-delta T cell" = 7062
"intrahepatic cholangiocyte" = 1309
"naive B cell" = 118
"B cell" = 2432
"plasmablast" = 42
"cholangiocyte" = 1154
"progenitor cell" = 1842
"centrilobular region hepatocyte" = 22161
"inflammatory macrophage" = 2282
"Kupffer cell" = 17807
"endothelial cell of pericentral hepatic sinusoid" = 8532
"endothelial cell of periportal hepatic sinusoid" = 1891
"blood vessel endothelial cell" = 519
"endothelial cell of hepatic sinusoid" = 3490
"endothelial cell of artery" = 76
"hepatocyte" = 30957
"macrophage" = 111755
"erythrocyte" = 119314
"periportal region hepatocyte" = 56964
"midzonal region hepatocyte" = 15100
"erythroblast" = 10264
"erythroid lineage cell" = 20
"liver dendritic cell" = 273
"monocyte" = 33725
"myeloid cell" = 1005
"classical monocyte" = 1603
"lymphocyte" = 235
"CD8-positive, alpha-beta T cell" = 634
"CD4-positive, alpha-beta T cell" = 661
"hepatic pit cell" = 509
"mature NK T cell" = 490
"T cell" = 10218
"neutrophil" = 195
"endothelial cell" = 13081
"conventional dendritic cell" = 1434
"plasmacytoid dendritic cell" = 6978
"myeloid leukocyte" = 2264
"non-classical monocyte" = 8300
"mast cell" = 4269
"megakaryocyte" = 18982
"hematopoietic stem cell" = 20508
"megakaryocyte-erythroid progenitor cell" = 14737
"precursor B cell" = 1365
"early T lineage precursor" = 197
"double negative thymocyte" = 241
"memory B cell" = 180
"germinal center B cell" = 1
"memory T cell" = 22154
"CD8-positive, alpha-beta memory T cell" = 24517
"naive thymus-derived CD4-positive, alpha-beta T cell" = 8651
"regulatory T cell" = 1300
"CD8-positive, alpha-beta cytotoxic T cell" = 10475
"hematopoietic multipotent progenitor cell" = 11010
"fraction A pre-pro B cell" = 4309
"early lymphoid progenitor" = 3380
"granulocyte monocyte progenitor cell" = 1561
"common myeloid progenitor" = 1742
"promyelocyte" = 2684
"promonocyte" = 2328
"alveolar macrophage" = 11
"dendritic cell, human" = 2
"innate lymphoid cell" = 939
"double-positive, alpha-beta thymocyte" = 123
"group 3 innate lymphoid cell" = 5064
"group 2 innate lymphoid cell" = 120
"CD8-alpha-alpha-positive, alpha-beta intraepithelial T cell" = 243
"naive thymus-derived CD8-positive, alpha-beta T cell" = 963
"CD8-positive, alpha-beta memory T cell, CD45RO-positive" = 806
"mucosal invariant T cell" = 2239
"CD16-negative, CD56-bright natural killer cell, human" = 1705
"CD16-positive, CD56-dim natural killer cell, human" = 1882
"effector memory CD8-positive, alpha-beta T cell, terminally differentiated" = 750
"effector memory CD4-positive, alpha-beta T cell" = 259
"T follicular helper cell" = 8
"CD4-positive helper T cell" = 587
"B-1 B cell" = 744
"large pre-B-II cell" = 6210
"pro-B cell" = 2952
"B-2 B cell" = 2180
"immature B cell" = 1956
"small pre-B-II cell" = 4132
"late pro-B cell" = 1570
"dendritic cell" = 15789
"granulocyte" = 1616
"pre-conventional dendritic cell" = 118
"common dendritic progenitor" = 50
"myelocyte" = 10
"Langerhans cell" = 4
"osteoclast" = 4
"mesothelial cell" = 153
"myofibroblast cell" = 136
"epithelial cell" = 45
"cell of skeletal muscle" = 1
"eurydendroid cell" = 4
"neuron" = 190
"skeletal muscle satellite cell" = 74
"smooth muscle cell" = 11
"glial cell" = 37
"epithelial cell of nephron" = 15
"keratinocyte" = 2
"enteroendocrine cell" = 3
"chondrocyte" = 1
"interstitial cell of Cajal" = 1
"hepatoblast" = 14401
"endothelial cell of vascular tree" = 1128