reference_name = "colon"
min_percentile = 0.1
LRI_database = "CPDBv5.0.0"

[celltype]
"macrophage" = 4539
"group 3 innate lymphoid cell" = 60
"dendritic cell" = 145
"mast cell" = 1921
"naive T cell" = 3199
"natural killer cell" = 762
"monocyte" = 311
"leukocyte" = 812
"plasmacytoid dendritic cell" = 1154
"B cell" = 3584
"precursor B cell" = 43
"vein endothelial cell" = 121
"myofibroblast cell" = 2091
"mesothelial cell" = 692
"IgA plasma cell" = 12
"pericyte" = 3410
"motor neuron" = 443
"interneuron" = 176
"glial cell" = 2387
"progenitor cell" = 3500
"neural cell" = 348
"inhibitory motor neuron" = 548
"neuroendocrine cell" = 82
"interstitial cell of Cajal" = 331
"enteric smooth muscle cell" = 5129
"smooth muscle cell of large intestine" = 1174
"smooth muscle cell of small intestine" = 13
"gut endothelial cell" = 2623
"activated CD8-positive, alpha-beta T cell" = 27
"memory T cell" = 9
"natural T-regulatory cell" = 6
"gamma-delta T cell" = 140
"fibroblast" = 22228
"endothelial cell" = 1267
"lymphocyte" = 24
"stromal cell" = 2554
"erythroid lineage cell" = 34
"secretory cell" = 162
"transit amplifying cell of colon" = 1034
"enterocyte" = 25990
"intestinal crypt stem cell of large intestine" = 1294
"intestine goblet cell" = 2893
"gut absorptive cell" = 1919
"enteroendocrine cell" = 539
"transit amplifying cell of small intestine" = 90
"intestinal crypt stem cell of small intestine" = 27
"plasma cell" = 21067
"memory B cell" = 39
"germinal center B cell" = 57
"naive B cell" = 29
"plasmablast" = 2
"regulatory T cell" = 1335
"CD4-positive, alpha-beta T cell" = 8257
"CD8-positive, alpha-beta T cell" = 3470
"innate lymphoid cell" = 235
"T cell" = 19
"conventional dendritic cell" = 326
"stem cell" = 10933
"epithelial cell" = 2872
"goblet cell" = 4587
"brush cell" = 382
"paneth cell" = 3
"alveolar macrophage" = 4
"classical monocyte" = 7
"alpha-beta T cell" = 46
"CD8-positive, alpha-beta memory T cell" = 104
"CD4-positive helper T cell" = 35
"effector memory CD8-positive, alpha-beta T cell, terminally differentiated" = 15
"T follicular helper cell" = 18
"CD8-positive, alpha-beta memory T cell, CD45RO-positive" = 14
"naive thymus-derived CD4-positive, alpha-beta T cell" = 5
"effector memory CD4-positive, alpha-beta T cell" = 8
"CD16-negative, CD56-bright natural killer cell, human" = 4
"mucosal invariant T cell" = 3
"CD16-positive, CD56-dim natural killer cell, human" = 3
"naive thymus-derived CD8-positive, alpha-beta T cell" = 1
"mesodermal cell" = 16861
"capillary endothelial cell" = 140
"type EC enteroendocrine cell" = 199
"oligodendrocyte precursor cell" = 843
"transit amplifying cell" = 781
"migratory enteric neural crest cell" = 846
"erythrocyte" = 123
"endothelial cell of artery" = 16
"NKp44-negative group 3 innate lymphoid cell, human" = 3
"neuroblast (sensu Vertebrata)" = 374
"enterocyte of colon" = 338
"primary sensory neuron (sensu Teleostei)" = 209
"megakaryocyte" = 8
"neutrophil" = 21
"pro-B cell" = 37
"common lymphoid progenitor" = 11
"endothelial cell of lymphatic vessel" = 42
"CD34-positive, CD56-positive, CD117-positive common innate lymphoid precursor, human" = 7
"progenitor cell of endocrine pancreas" = 5
"colon epithelial cell" = 211
"germ cell" = 14
"NKp44-positive group 3 innate lymphoid cell, human" = 1