[tool.poetry]
name = "fastccc"
version = "0.1.0"
description = ""
authors = ["Svvord <cchousiyu@163.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11, <3.13"
numpy = "^1.24"
pandas = "^2.2.3"
scipy = "^1.14.1"
scanpy = "^1.10.3"
loguru = "^0.7.2"
openpyxl = "^3.1.5"
gseapy = "^1.1.4"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
matplotlib = "^3.9.2"
seaborn = "^0.13.2"
cellxgene-census = "^1.16.2"
jinja2 = "^3.1.5"
psutil = "^6.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
