reference_name = "heart"
min_percentile = 0.1
LRI_database = "CPDBv5.0.0"

[celltype]
"neural cell" = 7903
"adipocyte" = 6509
"epicardial adipocyte" = 4266
"lymphocyte" = 22312
"cardiac neuron" = 3133
"regular atrial cardiac myocyte" = 49904
"CD4-positive, alpha-beta cytotoxic T cell" = 3113
"macrophage" = 15593
"mast cell" = 3882
"activated CD8-positive, alpha-beta T cell" = 3001
"natural killer cell" = 3628
"mature NK T cell" = 1476
"CD8-positive, alpha-beta cytotoxic T cell" = 2956
"dendritic cell" = 814
"monocyte" = 3567
"CD14-positive, CD16-positive monocyte" = 3278
"activated CD4-positive, alpha-beta T cell" = 1047
"B cell" = 1201
"fibroblast" = 140143
"cardiac endothelial cell" = 5330
"cardiac muscle cell" = 292702
"smooth muscle cell" = 19835
"fibroblast of cardiac tissue" = 61866
"myeloid cell" = 44230
"endothelial cell" = 150151
"pericyte" = 80758
"endocardial cell" = 2623
"innate lymphoid cell" = 2388
"fetal cardiomyocyte" = 81
"capillary endothelial cell" = 61256
"endothelial cell of artery" = 21068
"vein endothelial cell" = 9134
"neuron" = 836
"mesothelial cell of epicardium" = 705
"cardiac mesenchymal cell" = 2
"endothelial cell of lymphatic vessel" = 1645
"regular ventricular cardiac myocyte" = 268217
"mesothelial cell" = 1562
"mural cell" = 185081
"T cell" = 153
"erythrocyte" = 7
"plasma cell" = 5
"stromal cell" = 3151
"endothelial cell of vascular tree" = 1189
"dermis microvascular lymphatic vessel endothelial cell" = 139
"Schwann cell" = 134
"ventricular cardiac muscle cell" = 43
"visceromotor neuron" = 91
"megakaryocyte" = 78
"erythroblast" = 1