reference_name = "small_intestine"
min_percentile = 0.1
LRI_database = "CPDBv5.0.0"

[celltype]
"macrophage" = 1583
"mast cell" = 296
"dendritic cell" = 76
"monocyte" = 424
"plasmacytoid dendritic cell" = 107
"leukocyte" = 93
"group 3 innate lymphoid cell" = 229
"B cell" = 2789
"precursor B cell" = 52
"naive T cell" = 367
"natural killer cell" = 649
"vein endothelial cell" = 683
"endothelial cell of artery" = 109
"capillary endothelial cell" = 1680
"myofibroblast cell" = 947
"mesothelial cell" = 1350
"fibroblast" = 7974
"IgA plasma cell" = 1419
"IgG plasma cell" = 293
"memory B cell" = 1790
"pericyte" = 3972
"neural cell" = 170
"progenitor cell" = 10711
"glial cell" = 1597
"interneuron" = 58
"inhibitory motor neuron" = 1105
"motor neuron" = 1728
"neuroendocrine cell" = 41
"interstitial cell of Cajal" = 1157
"enteric smooth muscle cell" = 11437
"smooth muscle cell of small intestine" = 240
"smooth muscle cell of large intestine" = 18
"gut endothelial cell" = 1538
"activated CD8-positive, alpha-beta T cell" = 2060
"memory T cell" = 26
"gamma-delta T cell" = 6675
"natural T-regulatory cell" = 100
"CD4-positive helper T cell" = 3668
"CD4-positive, alpha-beta T cell" = 11182
"enterocyte of epithelium of large intestine" = 2042
"neutrophil" = 207
"transit amplifying cell of colon" = 313
"large intestine goblet cell" = 361
"CD8-positive, alpha-beta T cell" = 4810
"paneth cell of epithelium of small intestine" = 1294
"intestinal tuft cell" = 411
"plasma cell" = 1410
"intestinal enteroendocrine cell" = 116
"intestinal crypt stem cell of large intestine" = 204
"transit amplifying cell of small intestine" = 1054
"duodenum glandular cell" = 88
"erythroid lineage cell" = 5
"enterocyte" = 23979
"intestinal crypt stem cell of small intestine" = 748
"enteroendocrine cell" = 838
"secretory cell" = 199
"intestine goblet cell" = 5991
"gut absorptive cell" = 62
"naive B cell" = 2353
"lymphocyte" = 229
"germinal center B cell" = 2404
"plasmablast" = 3
"conventional dendritic cell" = 811
"alveolar macrophage" = 25
"non-classical monocyte" = 10
"classical monocyte" = 33
"dendritic cell, human" = 5
"stem cell" = 4632
"P/D1 enteroendocrine cell" = 18
"foveolar cell of stomach" = 6
"mucous neck cell" = 10
"peptic cell" = 2
"parietal cell" = 2
"type G enteroendocrine cell" = 2
"erythrocyte" = 1032
"CD8-positive, alpha-beta memory T cell" = 17034
"alpha-beta T cell" = 1112
"CD8-positive, alpha-beta memory T cell, CD45RO-positive" = 78
"regulatory T cell" = 356
"effector memory CD4-positive, alpha-beta T cell" = 97
"effector memory CD8-positive, alpha-beta T cell, terminally differentiated" = 309
"T follicular helper cell" = 880
"naive thymus-derived CD4-positive, alpha-beta T cell" = 312
"CD16-negative, CD56-bright natural killer cell, human" = 103
"CD16-positive, CD56-dim natural killer cell, human" = 29
"naive thymus-derived CD8-positive, alpha-beta T cell" = 13
"mucosal invariant T cell" = 78
"enterocyte of epithelium of small intestine" = 1100
"small intestine goblet cell" = 300
"intestinal crypt stem cell" = 102
"goblet cell" = 61
"enterocyte of colon" = 14948
"activated CD4-positive, alpha-beta T cell" = 533
"follicular dendritic cell" = 183
"T-helper 17 cell" = 397
"IgM plasma cell" = 259
"T-helper 1 cell" = 31
"transit amplifying cell" = 4354
"mature NK T cell" = 179
"stromal cell" = 22154
"inflammatory macrophage" = 105
"endothelial cell of lymphatic vessel" = 450
"reticular cell" = 105
"type L enteroendocrine cell" = 27
"M cell of gut" = 229
"type EC enteroendocrine cell" = 1383
"mesenchymal lymphangioblast" = 19
"type D enteroendocrine cell" = 83
"type N enteroendocrine cell" = 22
"epithelial cell" = 234
"progenitor cell of endocrine pancreas" = 289
"stromal cell of lamina propria of small intestine" = 20
"mesodermal cell" = 30463
"oligodendrocyte precursor cell" = 2064
"migratory enteric neural crest cell" = 1936
"type B pancreatic cell" = 31
"type I enteroendocrine cell" = 156
"neuroblast (sensu Vertebrata)" = 1434
"primary sensory neuron (sensu Teleostei)" = 645
"pro-B cell" = 134
"CD34-positive, CD56-positive, CD117-positive common innate lymphoid precursor, human" = 122
"NKp44-negative group 3 innate lymphoid cell, human" = 101
"common lymphoid progenitor" = 55
"NKp44-positive group 3 innate lymphoid cell, human" = 26
"T cell" = 14
"immature B cell" = 7
"GIP cell" = 19
"megakaryocyte" = 34
"colon epithelial cell" = 22
"group 2 innate lymphoid cell" = 5