reference_name = "thymus"
min_percentile = 0.1
LRI_database = "CPDBv5.0.0"

[celltype]
"medullary thymic epithelial cell" = 9381
"cortical thymic epithelial cell" = 9401
"epithelial cell of thymus" = 129
"precursor B cell" = 100
"double negative thymocyte" = 139527
"progenitor cell" = 75
"early T lineage precursor" = 211
"mast cell" = 348
"megakaryocyte" = 120
"erythrocyte" = 1233
"plasmacytoid dendritic cell" = 454
"hematopoietic stem cell" = 152
"megakaryocyte-erythroid progenitor cell" = 130
"memory B cell" = 3743
"lymphocyte" = 3
"plasma cell" = 3138
"naive B cell" = 1751
"germinal center B cell" = 1
"early lymphoid progenitor" = 743
"fraction A pre-pro B cell" = 315
"hematopoietic multipotent progenitor cell" = 36
"granulocyte monocyte progenitor cell" = 133
"common myeloid progenitor" = 146
"promonocyte" = 200
"promyelocyte" = 31
"CD4-positive helper T cell" = 15226
"naive regulatory T cell" = 1522
"T follicular helper cell" = 798
"CD8-positive, alpha-beta cytotoxic T cell" = 1002
"DN4 thymocyte" = 64
"B cell" = 3838
"fibroblast" = 22711
"macrophage" = 3043
"vascular associated smooth muscle cell" = 5295
"vein endothelial cell" = 4208
"capillary endothelial cell" = 2724
"endothelial cell of artery" = 1072
"mature NK T cell" = 548
"monocyte" = 1642
"endothelial cell of lymphatic vessel" = 542
"myeloid dendritic cell" = 6
"DN3 thymocyte" = 3576
"DN1 thymic pro-T cell" = 1970
"innate lymphoid cell" = 5242
"CD8-positive, alpha-beta T cell" = 7192
"mesothelial cell" = 26
"fast muscle cell" = 172
"dendritic cell" = 3626
"immature natural killer cell" = 88
"thymocyte" = 8031
"classical monocyte" = 1
"CD4-positive, alpha-beta T cell" = 6888
"double-positive, alpha-beta thymocyte" = 190950
"regulatory T cell" = 17448
"alpha-beta T cell" = 7102
"T cell" = 14897
"T-helper 17 cell" = 498
"gamma-delta T cell" = 2069
"natural killer cell" = 2191
"CD8-alpha-alpha-positive, alpha-beta intraepithelial T cell" = 14719
"naive thymus-derived CD8-positive, alpha-beta T cell" = 15829
"naive thymus-derived CD4-positive, alpha-beta T cell" = 19570
"group 3 innate lymphoid cell" = 580
"group 2 innate lymphoid cell" = 58
"effector memory CD8-positive, alpha-beta T cell, terminally differentiated" = 25
"effector memory CD4-positive, alpha-beta T cell" = 14
"CD16-positive, CD56-dim natural killer cell, human" = 2
"CD8-positive, alpha-beta memory T cell, CD45RO-positive" = 25
"mucosal invariant T cell" = 6
"mature B cell" = 203
"B-1 B cell" = 992
"B-2 B cell" = 360
"large pre-B-II cell" = 104
"pro-B cell" = 189
"immature B cell" = 60
"small pre-B-II cell" = 174
"late pro-B cell" = 165
"granulocyte" = 83
"osteoclast" = 15
"myelocyte" = 12
"neutrophil" = 18
"pre-conventional dendritic cell" = 8
"common dendritic progenitor" = 29
"Langerhans cell" = 28
"endothelial cell" = 640
"myofibroblast cell" = 1366
"skeletal muscle satellite cell" = 181
"keratinocyte" = 375
"stromal cell" = 146
"glial cell" = 384
"neuron" = 296
"epithelial cell" = 20
"eurydendroid cell" = 26
"enteroendocrine cell" = 11
"interstitial cell of Cajal" = 2
"smooth muscle cell" = 20
"chondrocyte" = 154
"epithelial cell of nephron" = 1
"cell of skeletal muscle" = 2
"professional antigen presenting cell" = 113
"endothelial cell of vascular tree" = 26