reference_name = "bone_marrow"
min_percentile = 0.1
LRI_database = "CPDBv5.0.0"

[celltype]
"monocyte" = 58044
"plasma cell" = 1892
"hematopoietic stem cell" = 3683
"erythroid progenitor cell" = 1514
"mature NK T cell" = 1356
"granulocyte" = 3662
"naive B cell" = 1049
"macrophage" = 6191
"common myeloid progenitor" = 7478
"memory B cell" = 1305
"CD8-positive, alpha-beta T cell" = 2294
"CD4-positive, alpha-beta T cell" = 4050
"neutrophil" = 8840
"plasmablast" = 183
"erythrocyte" = 55269
"pro-B cell" = 18304
"precursor B cell" = 72
"lymphocyte" = 847
"germinal center B cell" = 8
"hematopoietic multipotent progenitor cell" = 1731
"fraction A pre-pro B cell" = 6869
"granulocyte monocyte progenitor cell" = 12796
"early lymphoid progenitor" = 630
"megakaryocyte-erythroid progenitor cell" = 1199
"promonocyte" = 24906
"double negative thymocyte" = 146
"promyelocyte" = 5402
"megakaryocyte" = 7873
"classical monocyte" = 5032
"conventional dendritic cell" = 200
"non-classical monocyte" = 586
"alveolar macrophage" = 19
"natural killer cell" = 4016
"naive thymus-derived CD8-positive, alpha-beta T cell" = 1133
"group 3 innate lymphoid cell" = 387
"CD8-alpha-alpha-positive, alpha-beta intraepithelial T cell" = 60
"T cell" = 956
"naive thymus-derived CD4-positive, alpha-beta T cell" = 5610
"regulatory T cell" = 703
"double-positive, alpha-beta thymocyte" = 32
"innate lymphoid cell" = 44
"group 2 innate lymphoid cell" = 36
"effector memory CD8-positive, alpha-beta T cell, terminally differentiated" = 6684
"CD8-positive, alpha-beta memory T cell, CD45RO-positive" = 2895
"CD16-positive, CD56-dim natural killer cell, human" = 7394
"effector memory CD4-positive, alpha-beta T cell" = 2637
"mucosal invariant T cell" = 427
"gamma-delta T cell" = 1028
"CD16-negative, CD56-bright natural killer cell, human" = 832
"T follicular helper cell" = 267
"CD4-positive helper T cell" = 167
"alpha-beta T cell" = 301
"CD8-positive, alpha-beta memory T cell" = 63
"large pre-B-II cell" = 20706
"late pro-B cell" = 15663
"B-2 B cell" = 1554
"small pre-B-II cell" = 16371
"immature B cell" = 129
"B-1 B cell" = 291
"mature B cell" = 99
"pre-conventional dendritic cell" = 399
"mast cell" = 2367
"dendritic cell" = 4419
"myelocyte" = 2721
"common dendritic progenitor" = 195
"osteoclast" = 3573
"Kupffer cell" = 15
"plasmacytoid dendritic cell" = 2256
"fibroblast" = 231
"osteoblast" = 3468
"endothelial cell" = 1960
"vascular associated smooth muscle cell" = 12
"epithelial cell of nephron" = 2
"cell of skeletal muscle" = 62
"skeletal muscle satellite cell" = 30
"chondrocyte" = 160
"eurydendroid cell" = 2
"hepatocyte" = 2
"myofibroblast cell" = 8