reference_name = "spleen"
min_percentile = 0.1
LRI_database = "CPDBv5.0.0"

[celltype]
"memory B cell" = 27575
"naive B cell" = 8734
"plasma cell" = 8412
"lymphocyte" = 914
"plasmablast" = 875
"germinal center B cell" = 138
"pro-B cell" = 407
"precursor B cell" = 1
"hematopoietic multipotent progenitor cell" = 341
"megakaryocyte-erythroid progenitor cell" = 4330
"hematopoietic stem cell" = 739
"fraction A pre-pro B cell" = 1098
"early lymphoid progenitor" = 657
"megakaryocyte" = 13159
"granulocyte monocyte progenitor cell" = 350
"promyelocyte" = 243
"common myeloid progenitor" = 367
"promonocyte" = 507
"double negative thymocyte" = 22
"CD8-positive, alpha-beta memory T cell" = 9625
"macrophage" = 35340
"naive thymus-derived CD4-positive, alpha-beta T cell" = 14262
"intermediate monocyte" = 262
"endothelial cell" = 11144
"classical monocyte" = 14600
"neutrophil" = 9154
"CD4-positive, alpha-beta memory T cell" = 3542
"type I NK T cell" = 2076
"naive thymus-derived CD8-positive, alpha-beta T cell" = 8700
"mature NK T cell" = 4878
"innate lymphoid cell" = 857
"erythrocyte" = 6860
"regulatory T cell" = 6119
"platelet" = 58
"CD141-positive myeloid dendritic cell" = 102
"CD1c-positive myeloid dendritic cell" = 102
"plasmacytoid dendritic cell" = 1208
"CD8-positive, alpha-beta T cell" = 86
"conventional dendritic cell" = 303
"non-classical monocyte" = 254
"dendritic cell, human" = 19
"alveolar macrophage" = 38
"natural killer cell" = 39030
"T cell" = 14142
"CD8-alpha-alpha-positive, alpha-beta intraepithelial T cell" = 576
"group 3 innate lymphoid cell" = 4095
"group 2 innate lymphoid cell" = 120
"double-positive, alpha-beta thymocyte" = 399
"vascular associated smooth muscle cell" = 878
"effector memory CD4-positive, alpha-beta T cell" = 3837
"gamma-delta T cell" = 2104
"effector memory CD8-positive, alpha-beta T cell, terminally differentiated" = 3127
"mucosal invariant T cell" = 1519
"CD8-positive, alpha-beta memory T cell, CD45RO-positive" = 4984
"T follicular helper cell" = 4371
"CD16-negative, CD56-bright natural killer cell, human" = 3891
"CD16-positive, CD56-dim natural killer cell, human" = 4319
"alpha-beta T cell" = 703
"CD4-positive helper T cell" = 571
"B-2 B cell" = 28524
"large pre-B-II cell" = 206
"B-1 B cell" = 8880
"mature B cell" = 3270
"immature B cell" = 2324
"small pre-B-II cell" = 396
"late pro-B cell" = 204
"dendritic cell" = 4250
"mast cell" = 1240
"granulocyte" = 746
"myelocyte" = 108
"monocyte" = 4956
"fibroblast" = 34486
"Kupffer cell" = 230
"Langerhans cell" = 4
"common dendritic progenitor" = 40
"pre-conventional dendritic cell" = 14
"mesothelial cell" = 420
"myofibroblast cell" = 603
"glial cell" = 23
"smooth muscle cell" = 12
"neuron" = 3
"interstitial cell of Cajal" = 2
"eurydendroid cell" = 1
"stromal cell" = 468
"enteroendocrine cell" = 33
"epithelial cell" = 14
"endothelial cell of vascular tree" = 762
"hematopoietic cell" = 1096
"myeloid cell" = 301
"erythroblast" = 115