reference_name = "kidney"
min_percentile = 0.1
LRI_database = "CPDBv5.0.0"

[celltype]
"kidney loop of Henle thick ascending limb epithelial cell" = 38759
"capillary endothelial cell" = 851
"podocyte" = 3365
"urothelial cell" = 90
"vasa recta ascending limb cell" = 600
"renal alpha-intercalated cell" = 1634
"kidney epithelial cell" = 19583
"glomerular endothelial cell" = 1244
"renal intercalated cell" = 858
"renal beta-intercalated cell" = 552
"vasa recta descending limb cell" = 384
"progenitor cell" = 476
"kidney connecting tubule epithelial cell" = 11320
"myofibroblast cell" = 3862
"kidney interstitial fibroblast" = 16624
"epithelial cell of proximal tubule" = 84184
"renal principal cell" = 1604
"natural killer cell" = 7421
"CD4-positive, alpha-beta T cell" = 5750
"B cell" = 4271
"CD8-positive, alpha-beta T cell" = 2610
"classical monocyte" = 555
"neutrophil" = 697
"dendritic cell" = 3641
"mature NK T cell" = 1242
"kidney resident macrophage" = 87
"non-classical monocyte" = 797
"plasmacytoid dendritic cell" = 534
"mast cell" = 624
"macrophage" = 12813
"megakaryocyte" = 561
"monocyte" = 4792
"erythroid lineage cell" = 70
"conventional dendritic cell" = 2096
"lymphocyte" = 1499
"fibroblast" = 2051
"mesenchymal stem cell" = 5751
"neuron" = 61
"kidney cell" = 1918
"mesenchymal cell" = 5117
"kidney loop of Henle epithelial cell" = 121
"peritubular capillary endothelial cell" = 851
"epithelial cell of glomerular capsule" = 651
"mononuclear phagocyte" = 3364
"endothelial cell" = 26211
"CD4-positive helper T cell" = 362
"kidney interstitial cell" = 7946
"epithelial cell of nephron" = 18241
"nephron tubule epithelial cell" = 495
"kidney collecting duct cell" = 420
"innate lymphoid cell" = 352
"kidney distal convoluted tubule epithelial cell" = 15258
"parietal epithelial cell" = 2000
"kidney loop of Henle thin ascending limb epithelial cell" = 6257
"mesangial cell" = 11167
"leukocyte" = 40
"fraction A pre-pro B cell" = 93
"early lymphoid progenitor" = 137
"hematopoietic multipotent progenitor cell" = 22
"double negative thymocyte" = 11
"promonocyte" = 396
"granulocyte monocyte progenitor cell" = 47
"promyelocyte" = 35
"megakaryocyte-erythroid progenitor cell" = 12
"common myeloid progenitor" = 11
"kidney interstitial alternatively activated macrophage" = 2717
"T cell" = 4404
"kidney collecting duct intercalated cell" = 13414
"kidney collecting duct principal cell" = 22750
"plasmacytoid dendritic cell, human" = 66
"plasma cell" = 223
"kidney loop of Henle thin descending limb epithelial cell" = 8501
"renal interstitial pericyte" = 4947
"papillary tips cell" = 722
"neural cell" = 70
"regulatory T cell" = 339
"naive thymus-derived CD8-positive, alpha-beta T cell" = 580
"naive thymus-derived CD4-positive, alpha-beta T cell" = 1367
"group 3 innate lymphoid cell" = 225
"double-positive, alpha-beta thymocyte" = 6
"group 2 innate lymphoid cell" = 34
"CD8-alpha-alpha-positive, alpha-beta intraepithelial T cell" = 26
"erythrocyte" = 34
"vascular associated smooth muscle cell" = 12157
"cytotoxic T cell" = 97
"large pre-B-II cell" = 257
"pro-B cell" = 125
"B-2 B cell" = 299
"mature B cell" = 14
"B-1 B cell" = 49
"small pre-B-II cell" = 297
"late pro-B cell" = 47
"immature B cell" = 167
"granulocyte" = 53
"common dendritic progenitor" = 16
"pre-conventional dendritic cell" = 9
"Kupffer cell" = 6
"Langerhans cell" = 3
"hematopoietic stem cell" = 3
"myelocyte" = 9
"epithelial cell" = 3329
"keratinocyte" = 5
"stromal cell" = 275
"glial cell" = 26
"skeletal muscle satellite cell" = 16
"eurydendroid cell" = 8
"hepatocyte" = 2
"mesothelial cell" = 7
"smooth muscle cell" = 19
"interstitial cell of Cajal" = 1
"endothelial cell of vascular tree" = 1455
"taste receptor cell" = 2382
"myeloid cell" = 840
"erythroblast" = 50