reference_name = "prostate_gland"
min_percentile = 0.1
LRI_database = "CPDBv5.0.0"

[celltype]
"fibroblast of connective tissue of prostate" = 2921
"smooth muscle cell of prostate" = 2806
"fibroblast of connective tissue of glandular part of prostate" = 684
"fibroblast of connective tissue of nonglandular part of prostate" = 323
"pericyte" = 272
"vascular associated smooth muscle cell" = 158
"basal cell of prostate epithelium" = 80941
"luminal cell of prostate epithelium" = 10553
"epithelial cell of urethra" = 14756
"secretory cell" = 9152
"neuroendocrine cell" = 90
"prostate gland microvascular endothelial cell" = 2368
"leukocyte" = 663
"non-classical monocyte" = 18
"dendritic cell" = 81
"classical monocyte" = 24
"CD1c-positive myeloid dendritic cell" = 86
"CD4-positive, alpha-beta thymocyte" = 107
"granulocyte" = 23
"effector CD4-positive, alpha-beta T cell" = 15
"B cell" = 5
"CD141-positive myeloid dendritic cell" = 3
"mature NK T cell" = 863
"plasma cell" = 8
"effector CD8-positive, alpha-beta T cell" = 1
"prostate stromal cell" = 585
"epithelial cell" = 13696
"fibroblast" = 446
"club cell" = 2156
"macrophage" = 999
"erythroid progenitor cell" = 172
"CD8-positive, alpha-beta T cell" = 2162
"endothelial cell" = 1170
"smooth muscle cell" = 570
"stromal cell" = 64
"monocyte" = 66
"T cell" = 1172
"neutrophil" = 32
"sperm" = 11
"mast cell" = 18
"myeloid cell" = 365