reference_name = "stomach"
min_percentile = 0.1
LRI_database = "CPDBv5.0.0"

[celltype]
"dendritic cell" = 248
"macrophage" = 336
"monocyte" = 308
"mast cell" = 534
"vein endothelial cell" = 1234
"endothelial cell of artery" = 1624
"capillary endothelial cell" = 494
"fibroblast" = 4368
"IgA plasma cell" = 3194
"memory B cell" = 1056
"IgG plasma cell" = 672
"natural killer cell" = 328
"activated CD8-positive, alpha-beta T cell" = 4954
"gamma-delta T cell" = 3060
"memory T cell" = 3096
"CD4-positive helper T cell" = 1464
"natural T-regulatory cell" = 2886
"foveolar cell of stomach" = 12538
"mucous neck cell" = 4100
"enteroendocrine cell" = 960
"enterocyte" = 534
"peptic cell" = 2302
"parietal cell" = 700
"P/D1 enteroendocrine cell" = 1368
"stem cell" = 318
"intestine goblet cell" = 118
"type G enteroendocrine cell" = 14
"erythrocyte" = 99
"epithelial cell of esophagus" = 26
"glandular cell of esophagus" = 20
"erythroblast" = 33
"goblet cell" = 900
"squamous epithelial cell" = 507
"ciliated epithelial cell" = 80
"innate lymphoid cell" = 116
"stromal cell" = 378
"mesothelial cell" = 47
"neuroendocrine cell" = 82
"enteric neuron" = 12
"endothelial cell of lymphatic vessel" = 21
"brush cell" = 198
"glial cell" = 24
"endothelial cell of vascular tree" = 87
"myeloid cell" = 36