reference_name = "lung"
min_percentile = 0.1
LRI_database = "CPDBv5.0.0"

[celltype]
"Schwann cell" = 139
"immature Schwann cell" = 33
"neuron" = 270
"Schwann cell precursor" = 192
"neural progenitor cell" = 15
"lung ciliated cell" = 2845
"memory B cell" = 961
"IgG plasma cell" = 405
"IgA plasma cell" = 513
"plasmablast" = 69
"naive B cell" = 424
"small pre-B-II cell" = 453
"large pre-B-II cell" = 546
"B-1b B cell" = 555
"immature B cell" = 526
"pro-B cell" = 135
"pre-B-I cell" = 542
"late pro-B cell" = 452
"precursor B cell" = 650
"B-1a B cell" = 279
"CD4-positive, alpha-beta memory T cell" = 638
"CD16-positive, CD56-dim natural killer cell, human" = 3458
"CD16-negative, CD56-bright natural killer cell, human" = 1214
"natural killer cell" = 70093
"T-helper 17 cell" = 167
"regulatory T cell" = 2869
"CD8-positive, alpha-beta T cell" = 61059
"T cell" = 36082
"type II NK T cell" = 147
"type I NK T cell" = 123
"group 3 innate lymphoid cell" = 175
"group 2 innate lymphoid cell" = 149
"CD34-positive, CD56-positive, CD117-positive common innate lymphoid precursor, human" = 80
"thymocyte" = 12
"smooth muscle cell of the pulmonary artery" = 1470
"blood vessel smooth muscle cell" = 175
"lung pericyte" = 6573
"smooth muscle cell" = 3993
"erythrocyte" = 897
"capillary endothelial cell" = 76616
"endothelial cell of lymphatic vessel" = 18741
"vein endothelial cell" = 33193
"endothelial cell of artery" = 7482
"reticulocyte" = 300
"erythroblast" = 123
"endothelial cell" = 117
"primitive red blood cell" = 305
"type II pneumocyte" = 238113
"macrophage" = 178628
"dendritic cell" = 9869
"classical monocyte" = 98362
"non-classical monocyte" = 16927
"promonocyte" = 124
"hematopoietic stem cell" = 123
"dendritic cell, human" = 282
"neutrophil" = 816
"megakaryocyte" = 135
"promyelocyte" = 36
"plasmacytoid dendritic cell" = 1269
"eosinophil" = 13
"basophil" = 1379
"megakaryocyte-erythroid progenitor cell" = 28
"platelet" = 21
"early lymphoid progenitor" = 21
"granulocyte monocyte progenitor cell" = 29
"bone marrow cell" = 36
"common myeloid progenitor" = 7
"effector memory CD8-positive, alpha-beta T cell" = 3827
"innate lymphoid cell" = 886
"mucosal invariant T cell" = 819
"effector CD4-positive, alpha-beta T cell" = 5039
"lung resident memory CD8-positive, alpha-beta T cell" = 2563
"lung resident memory CD4-positive, alpha-beta T cell" = 1304
"naive thymus-derived CD4-positive, alpha-beta T cell" = 2828
"gamma-delta T cell" = 782
"epithelial cell of lung" = 19439
"club cell" = 7309
"respiratory epithelial cell" = 2846
"squamous epithelial cell" = 81
"type I pneumocyte" = 31638
"lung secretory cell" = 3276
"neuroendocrine cell" = 1166
"glandular epithelial cell" = 7
"lung neuroendocrine cell" = 157
"basal cell" = 6631
"blood vessel endothelial cell" = 9961
"pulmonary artery endothelial cell" = 14964
"adventitial cell" = 5809
"myofibroblast cell" = 3251
"fibroblast of lung" = 37244
"fibroblast" = 18437
"mesothelial cell" = 1261
"bronchus fibroblast of lung" = 2141
"non-myelinating Schwann cell" = 60
"myelinating Schwann cell" = 4
"lung perichondrial fibroblast" = 172
"epithelial cell of alveolus of lung" = 2332
"ciliated epithelial cell" = 911
"goblet cell" = 833
"hepatocyte" = 170
"ionocyte" = 241
"brush cell" = 2
"ciliated cell" = 1861
"epithelial cell" = 12
"deuterosomal cell" = 41
"airway submucosal gland duct basal cell" = 329
"respiratory suprabasal cell" = 350
"serous secreting cell of bronchus submucosal gland" = 2494
"myoepithelial cell" = 264
"monocyte" = 25961
"lung macrophage" = 10483
"alveolar macrophage" = 214671
"CD14-positive monocyte" = 2748
"conventional dendritic cell" = 2738
"lung interstitial macrophage" = 207
"metallothionein-positive alveolar macrophage" = 304
"pulmonary interstitial fibroblast" = 8289
"pericyte" = 4075
"vascular associated smooth muscle cell" = 807
"tracheobronchial smooth muscle cell" = 7263
"chondrocyte" = 103
"mesenchymal cell" = 324
"plasma cell" = 4595
"lymphocyte" = 240
"germinal center B cell" = 4
"lung microvascular endothelial cell" = 970
"effector CD8-positive, alpha-beta T cell" = 1744
"mature NK T cell" = 264
"respiratory goblet cell" = 1524
"CD4-positive, alpha-beta T cell" = 55351
"B cell" = 16365
"serous cell of epithelium of bronchus" = 30
"bronchial smooth muscle cell" = 162
"intermediate monocyte" = 504
"pulmonary ionocyte" = 38
"CD4-positive helper T cell" = 4122
"CD8-positive, alpha-beta memory T cell" = 701
"exhausted T cell" = 17
"alpha-beta T cell" = 248
"effector memory CD8-positive, alpha-beta T cell, terminally differentiated" = 945
"CD8-positive, alpha-beta memory T cell, CD45RO-positive" = 417
"effector memory CD4-positive, alpha-beta T cell" = 947
"naive thymus-derived CD8-positive, alpha-beta T cell" = 39
"T follicular helper cell" = 79
"myeloid cell" = 6601
"mast cell" = 22677
"epithelial cell of lower respiratory tract" = 30409
"stromal cell" = 21542
"endothelial cell of vascular tree" = 3265
"visceromotor neuron" = 55
"NKp46-positive innate lymphoid cell, human" = 14878
"secretory cell" = 6551
"multi-ciliated epithelial cell" = 19732
"fibrocyte" = 57
"elicited macrophage" = 32577
"respiratory basal cell" = 5280
"ciliated columnar cell of tracheobronchial tree" = 16819
"alveolar type 1 fibroblast cell" = 12725
"alveolar type 2 fibroblast cell" = 16855
"CD1c-positive myeloid dendritic cell" = 16212
"bronchial goblet cell" = 132
"respiratory hillock cell" = 70
"nasal mucosa goblet cell" = 344
"tracheobronchial goblet cell" = 16
"acinar cell" = 175
"mucus secreting cell" = 416
"brush cell of trachebronchial tree" = 5
"malignant cell" = 2624
"tracheobronchial serous cell" = 405
"serous secreting cell" = 31