reference_name = "lymph_node"
min_percentile = 0.1
LRI_database = "CPDBv5.0.0"

[celltype]
"naive B cell" = 8729
"memory B cell" = 20456
"plasma cell" = 5925
"germinal center B cell" = 347
"lymphocyte" = 687
"plasmablast" = 543
"pro-B cell" = 37
"early lymphoid progenitor" = 265
"fraction A pre-pro B cell" = 66
"common myeloid progenitor" = 18
"double negative thymocyte" = 61
"hematopoietic multipotent progenitor cell" = 7
"hematopoietic stem cell" = 77
"megakaryocyte-erythroid progenitor cell" = 14
"granulocyte monocyte progenitor cell" = 4
"classical monocyte" = 635
"conventional dendritic cell" = 196
"macrophage" = 3018
"alveolar macrophage" = 114
"dendritic cell, human" = 143
"non-classical monocyte" = 82
"endothelial cell" = 508
"B cell" = 30498
"effector CD8-positive, alpha-beta T cell" = 11720
"T cell" = 9868
"type I NK T cell" = 7516
"effector CD4-positive, alpha-beta T cell" = 13816
"innate lymphoid cell" = 4852
"regulatory T cell" = 12937
"neutrophil" = 214
"mature NK T cell" = 1366
"CD141-positive myeloid dendritic cell" = 202
"CD1c-positive myeloid dendritic cell" = 180
"intermediate monocyte" = 612
"mast cell" = 301
"plasmacytoid dendritic cell" = 106
"stromal cell" = 689
"erythrocyte" = 93
"mature conventional dendritic cell" = 34
"naive thymus-derived CD4-positive, alpha-beta T cell" = 30144
"CD4-positive, alpha-beta memory T cell" = 2868
"CD8-positive, alpha-beta memory T cell" = 2330
"CD8-alpha-alpha-positive, alpha-beta intraepithelial T cell" = 240
"natural killer cell" = 1264
"naive thymus-derived CD8-positive, alpha-beta T cell" = 9024
"double-positive, alpha-beta thymocyte" = 248
"group 3 innate lymphoid cell" = 1204
"group 2 innate lymphoid cell" = 4
"promyelocyte" = 18
"effector memory CD4-positive, alpha-beta T cell" = 7608
"CD8-positive, alpha-beta memory T cell, CD45RO-positive" = 2414
"CD16-negative, CD56-bright natural killer cell, human" = 1367
"T follicular helper cell" = 10349
"alpha-beta T cell" = 1949
"CD4-positive helper T cell" = 1358
"mucosal invariant T cell" = 305
"effector memory CD8-positive, alpha-beta T cell, terminally differentiated" = 398
"CD16-positive, CD56-dim natural killer cell, human" = 435
"gamma-delta T cell" = 293
"mature B cell" = 54
"large pre-B-II cell" = 126
"B-1 B cell" = 465
"B-2 B cell" = 693
"immature B cell" = 93
"small pre-B-II cell" = 348
"late pro-B cell" = 93
"dendritic cell" = 495
"fibroblast" = 89
"promonocyte" = 24
"monocyte" = 66
"granulocyte" = 24
"common dendritic progenitor" = 3
"vascular associated smooth muscle cell" = 208
"glial cell" = 67
"myofibroblast cell" = 328
"neuron" = 2
"endothelial cell of lymphatic vessel" = 325
"capillary endothelial cell" = 69
"vein endothelial cell" = 125
"endothelial cell of artery" = 99
"CD8-positive, alpha-beta T cell" = 1
"CD4-positive, alpha-beta T cell" = 2
"pericyte" = 9
"reticular cell" = 3
"IgG plasma cell" = 1