reference_name = "blood"
min_percentile = 0.1
LRI_database = "CPDBv5.0.0"

[celltype]
"platelet" = 2904
"CD38-negative naive B cell" = 11681
"unswitched memory B cell" = 5279
"plasmablast" = 620
"B-2 B cell" = 434
"naive B cell" = 14614
"memory B cell" = 6189
"transitional stage B cell" = 5191
"IgA plasmablast" = 188
"IgG plasmablast" = 58
"mucosal invariant T cell" = 4285
"natural killer cell" = 58342
"gamma-delta T cell" = 6052
"CD16-negative, CD56-bright natural killer cell, human" = 2336
"classical monocyte" = 97661
"erythrocyte" = 21363
"effector memory CD8-positive, alpha-beta T cell" = 29126
"non-classical monocyte" = 12884
"naive thymus-derived CD4-positive, alpha-beta T cell" = 51681
"conventional dendritic cell" = 3663
"central memory CD4-positive, alpha-beta T cell" = 43446
"neutrophil" = 16969
"lymphocyte" = 1389
"regulatory T cell" = 4708
"naive thymus-derived CD8-positive, alpha-beta T cell" = 18640
"hematopoietic stem cell" = 624
"plasmacytoid dendritic cell, human" = 1839
"double negative thymocyte" = 200
"activated CD4-positive, alpha-beta T cell, human" = 75
"immature neutrophil" = 4
"plasmacytoid dendritic cell" = 783
"dendritic cell" = 1969
"intermediate monocyte" = 546
"monocyte" = 23416
"CD4-positive, alpha-beta cytotoxic T cell" = 2332
"effector CD8-positive, alpha-beta T cell" = 9114
"activated CD4-positive, alpha-beta T cell" = 202
"T cell" = 467
"plasma cell" = 1042
"macrophage" = 982
"alveolar macrophage" = 7
"activated CD8-positive, alpha-beta T cell, human" = 2
"CD4-positive, alpha-beta memory T cell" = 1898
"CD8-positive, alpha-beta cytokine secreting effector T cell" = 2986
"mature NK T cell" = 5896
"type I NK T cell" = 1036
"CD141-positive myeloid dendritic cell" = 30
"CD8-positive, alpha-beta T cell" = 2644
"basophil" = 58
"CD4-positive, alpha-beta T cell" = 5726
"common myeloid progenitor" = 6
"granulocyte" = 4
"effector memory CD4-positive, alpha-beta T cell" = 4331
"effector memory CD8-positive, alpha-beta T cell, terminally differentiated" = 1983
"CD4-positive helper T cell" = 35
"CD16-positive, CD56-dim natural killer cell, human" = 3539
"alpha-beta T cell" = 270
"CD8-positive, alpha-beta memory T cell, CD45RO-positive" = 635
"group 3 innate lymphoid cell" = 15
"CD8-positive, alpha-beta memory T cell" = 9
"T follicular helper cell" = 111