reference_name = "eye"
min_percentile = 0.1
LRI_database = "CPDBv5.0.0"

[celltype]
"myeloid cell" = 790
"retinal cone cell" = 32016
"S cone cell" = 1563
"retinal pigment epithelial cell" = 8365
"retina horizontal cell" = 9757
"OFF retinal ganglion cell" = 1124
"ON retinal ganglion cell" = 549
"retinal ganglion cell" = 15406
"amacrine cell" = 117742
"A2 amacrine cell" = 1070
"glycinergic amacrine cell" = 116738
"starburst amacrine cell" = 20779
"pericyte" = 775
"Mueller cell" = 94110
"melanocyte" = 4632
"astrocyte" = 4881
"B cell" = 245
"T cell" = 561
"Schwann cell" = 3224
"endothelial cell" = 1723
"ON-bipolar cell" = 38243
"OFF-bipolar cell" = 31337
"conjunctival epithelial cell" = 10877
"monocyte" = 88
"microglial cell" = 4231
"eye photoreceptor cell" = 1782
"fibroblast" = 7713
"stem cell" = 288
"retinal blood vessel endothelial cell" = 932
"epithelial cell of lacrimal sac" = 104
"keratocyte" = 1190
"corneal epithelial cell" = 6922
"stromal cell" = 907
"retinal bipolar neuron" = 104299
"dendritic cell" = 364
"plasma cell" = 92
"macrophage" = 3149
"erythroid lineage cell" = 60
"radial glial cell" = 390
"surface ectodermal cell" = 108
"CD8-positive, alpha-beta T cell" = 16
"pigmented ciliary epithelial cell" = 1032
"CD4-positive, alpha-beta T cell" = 46
"mast cell" = 56
"adipocyte" = 88
"retinal rod cell" = 325718
"non-pigmented ciliary epithelial cell" = 997
"ciliary muscle cell" = 2933
"lymphocyte" = 993
"blood vessel endothelial cell" = 586
"basal cell" = 4164
"corneal endothelial cell" = 1926
"transit amplifying cell" = 374
"leukocyte" = 192
"pigmented epithelial cell" = 2000
"smooth muscle cell of sphincter of pupil" = 935
"endothelial cell of lymphatic vessel" = 997
"goblet cell" = 293
"invaginating midget bipolar cell" = 77766
"flat midget bipolar cell" = 116584
"rod bipolar cell" = 102966
"OFFx cell" = 14562
"diffuse bipolar 2 cell" = 58198
"diffuse bipolar 1 cell" = 41177
"ON-blue cone bipolar cell" = 2351
"diffuse bipolar 3a cell" = 16642
"diffuse bipolar 4 cell" = 39001
"diffuse bipolar 3b cell" = 30254
"giant bipolar cell" = 21654
"diffuse bipolar 6 cell" = 17339
"midget ganglion cell of retina" = 111332
"parasol ganglion cell of retina" = 2544
"GABAergic amacrine cell" = 302439
"H1 horizontal cell" = 17663
"H2 horizontal cell" = 3584
"photoreceptor cell" = 3009
"ganglion interneuron" = 317
"lens fiber cell" = 68
"bipolar neuron" = 292
"endothelial cell of vascular tree" = 55
"smooth muscle cell" = 11
"cell of skeletal muscle" = 32