title: FastCCC
description: FastCCC's tutorial.
remote_theme: just-the-docs/just-the-docs

baseurl: /FastCCC
url: https://svvord.github.io

aux_links:
  Source code: https://github.com/Svvord/FastCCC
