reference_name = "skin"
min_percentile = 0.1
LRI_database = "CPDBv5.0.0"

[celltype]
"skin fibroblast" = 14684
"hair follicular keratinocyte" = 2649
"basal cell of epidermis" = 1339
"keratinocyte" = 11412
"sebum secreting cell" = 87
"granular cell of epidermis" = 46
"macrophage" = 39332
"stromal cell" = 5898
"CD8-positive, alpha-beta memory T cell" = 1714
"CD141-positive myeloid dendritic cell" = 34
"T cell" = 5793
"mature NK T cell" = 1210
"mast cell" = 2815
"muscle cell" = 874
"CD8-positive, alpha-beta cytotoxic T cell" = 258
"CD1c-positive myeloid dendritic cell" = 330
"endothelial cell" = 5029
"CD4-positive, alpha-beta memory T cell" = 678
"naive thymus-derived CD8-positive, alpha-beta T cell" = 4310
"naive thymus-derived CD4-positive, alpha-beta T cell" = 10081
"melanocyte" = 1027
"regulatory T cell" = 3429
"epithelial cell" = 249
"plasma cell" = 75
"CD4-positive helper T cell" = 118
"memory B cell" = 18
"Langerhans cell" = 170
"naive B cell" = 14
"smooth muscle cell" = 55
"cell of skeletal muscle" = 109
"fraction A pre-pro B cell" = 396
"early lymphoid progenitor" = 663
"megakaryocyte-erythroid progenitor cell" = 577
"double negative thymocyte" = 82
"hematopoietic stem cell" = 195
"hematopoietic multipotent progenitor cell" = 122
"common myeloid progenitor" = 73
"granulocyte monocyte progenitor cell" = 306
"promyelocyte" = 135
"promonocyte" = 1221
"megakaryocyte" = 894
"innate lymphoid cell" = 658
"conventional dendritic cell" = 1640
"pericyte" = 1047
"helper T cell" = 412
"fibroblast" = 104008
"suprabasal keratinocyte" = 2085
"chondrocyte" = 71
"plasmacytoid dendritic cell" = 1361
"endothelial cell of vascular tree" = 1400
"CD8-positive, alpha-beta memory T cell, CD45RO-positive" = 263
"Schwann cell" = 10
"endothelial cell of lymphatic vessel" = 246
"monocyte" = 11934
"natural killer cell" = 15443
"dendritic cell" = 7927
"melanocyte of skin" = 74
"cytotoxic T cell" = 15
"basal cell" = 2
"group 3 innate lymphoid cell" = 5121
"group 2 innate lymphoid cell" = 972
"double-positive, alpha-beta thymocyte" = 243
"CD8-alpha-alpha-positive, alpha-beta intraepithelial T cell" = 105
"erythrocyte" = 1938
"vascular associated smooth muscle cell" = 9432
"large pre-B-II cell" = 254
"pro-B cell" = 350
"mature B cell" = 98
"small pre-B-II cell" = 444
"B-2 B cell" = 1918
"B-1 B cell" = 348
"immature B cell" = 770
"late pro-B cell" = 202
"pre-conventional dendritic cell" = 12
"granulocyte" = 430
"myelocyte" = 88
"neutrophil" = 32
"common dendritic progenitor" = 48
"Kupffer cell" = 22
"osteoclast" = 2
"eurydendroid cell" = 1244
"myofibroblast cell" = 5228
"glial cell" = 4380
"skeletal muscle satellite cell" = 5768
"enteroendocrine cell" = 1
"neuron" = 637
"epithelial cell of nephron" = 149
"mesothelial cell" = 1
"hepatocyte" = 1