reference_name = "breast"
min_percentile = 0.1
LRI_database = "CPDBv5.0.0"

[celltype]
"endothelial cell of lymphatic vessel" = 45986
"naive B cell" = 7207
"class switched memory B cell" = 10089
"IgG plasma cell" = 1076
"IgA plasma cell" = 5233
"unswitched memory B cell" = 1993
"CD8-positive, alpha-beta memory T cell" = 55017
"naive thymus-derived CD4-positive, alpha-beta T cell" = 27160
"Tc1 cell" = 12455
"macrophage" = 35379
"CD4-positive helper T cell" = 45066
"plasma cell" = 7649
"effector memory CD8-positive, alpha-beta T cell" = 16719
"natural killer cell" = 5638
"innate lymphoid cell" = 787
"dendritic cell" = 2036
"mature NK T cell" = 10625
"classical monocyte" = 4166
"myeloid dendritic cell" = 455
"non-classical monocyte" = 996
"conventional dendritic cell" = 3985
"alternatively activated macrophage" = 9059
"inflammatory macrophage" = 8853
"myeloid cell" = 406
"plasmacytoid dendritic cell" = 148
"neutrophil" = 442
"mast cell" = 664
"pericyte" = 24710
"vascular associated smooth muscle cell" = 27928
"CD4-positive, alpha-beta T cell" = 5199
"gamma-delta T cell" = 529
"regulatory T cell" = 2365
"lymphocyte" = 1667
"activated CD4-positive, alpha-beta T cell" = 2123
"effector memory CD4-positive, alpha-beta T cell" = 4883
"activated CD8-positive, alpha-beta T cell" = 1032
"T cell" = 259
"capillary endothelial cell" = 73185
"vein endothelial cell" = 195102
"endothelial cell of artery" = 85250
"fibroblast" = 208390
"luminal epithelial cell of mammary gland" = 104415
"mammary gland epithelial cell" = 36270
"basal cell" = 102228
"fibroblast of mammary gland" = 563042
"endothelial tip cell" = 76298
"perivascular cell" = 236347
"luminal adaptive secretory precursor cell of mammary gland" = 445593
"luminal hormone-sensing cell of mammary gland" = 332133
"myoepithelial cell of mammary gland" = 168262